176755913 design refactor
UseHover/Stax pull request #31
Opened 2021-02-02 01:08 UTC by davkutalek

This is a work in progress.

This creates re-useable ChannelDropdown and ActionSelect UI components. The Channel dropdown includes settings for how it behaves on the balance screen vs. the transfer screen. The abstract StagedX components have been paired down considerably, and I am attempting to turn the interactions between the UI components and the viewmodel into an interface to reduce duplication.

The balances screen is fully working and the transfer/buy airtime screen is mostly working with a minor bugs. Requests are untested and unmerged with the latest from designV3.

2021-02-04 01:27 UTC, davkutalek commented
@androidmaven this is ready for basic QA though it still has some issues. Since every screen has been changed it needs QA basically everywhere.

There are still some bugs that I am aware of:
- Vertical margin between input elements is uneven. - I could use help with this, I can't figure it out.
- When loading a link the channel is not always selected correctly. - I have a fix in progress.
- Transaction history and Future transactions show when they shouldn't but also don't load transactions correctly. - I think there is simple fix

2021-02-04 16:05 UTC, androidmaven requested changes
Huge kudos with the changes, the approach is really good.

Spotted some additional bugs.

2021-02-04 16:55 UTC, davkutalek commented on app/src/main/java/com/hover/stax/balances/BalancesFragment.java
> +		channelDropdownViewModel.getChannels().observe(getViewLifecycleOwner(), channels -> channelDropdown.updateChannels(channels));
Yeah, I originally thought if simChannels came up empty we should load all, but I think just showing an error may be a better approach. Prob should ask justin

2021-02-04 16:57 UTC, davkutalek commented on app/src/main/java/com/hover/stax/balances/BalancesFragment.java
> +				balancesViewModel.setAllRunning(v.getContext());
hmm, this works for me. Can you give me a little more detail or a screenshot of what happens?

2021-02-04 17:00 UTC, davkutalek commented on app/src/main/java/com/hover/stax/channels/ChannelDropdownViewModel.java
> +				return getApplication().getString(R.string.check_balance);
There are no actions for Request money and this is only used for showing errors related to loading actions

2021-02-05 14:40 UTC, androidmaven commented on app/src/main/java/com/hover/stax/balances/BalancesFragment.java
> +		channelDropdownViewModel.getChannels().observe(getViewLifecycleOwner(), channels -> channelDropdown.updateChannels(channels));
I think its fine for now. However, on first load; it shows all channels even when sim channels has loaded.

2021-02-05 14:53 UTC, androidmaven commented on app/src/main/java/com/hover/stax/channels/ChannelDropdownViewModel.java
> +	}
Works now. I think it might have been my sdk branch or somehting

2021-02-05 14:53 UTC, androidmaven commented on app/src/main/java/com/hover/stax/channels/ChannelDropdownViewModel.java
> +				return getApplication().getString(R.string.check_balance);
Alright, thanks.

2021-02-05 14:53 UTC, androidmaven commented on app/src/main/java/com/hover/stax/balances/BalancesFragment.java
> +				balancesViewModel.setAllRunning(v.getContext());
Works now

2021-02-05 14:55 UTC, androidmaven approved these changes
I've QA'ed the app, also gone through codebase again. Looks good. Would still do another round of QA later today.

2021-02-05 18:25 UTC, merged