179194009 paybill
UseHover/Stax pull request #377
Opened 2022-01-12 15:20 UTC by alexosugo

Paybill support.

2022-01-12 20:10 UTC, davkutalek approved these changes
Code looks great, no issues. There are some fairly minor functional and QA issues, see pivotal for those details.

2022-01-12 22:01 UTC, androidmaven requested changes
This is work super done... I've also picked up a couple of things from this -> Thank you!

Just some minor comments, however.

2022-01-13 11:53 UTC, alexosugo commented on app/src/main/java/com/hover/stax/paybill/PaybillActionsAdapter.kt
> +class PaybillActionsAdapter(private val paybillActions: List<HoverAction>, private val clickListener: ClickListener) : RecyclerView.Adapter<PaybillActionsAdapter.ActionsViewHolder>() {
Sure, I can rename this.

2022-01-13 11:55 UTC, alexosugo commented on app/src/main/java/com/hover/stax/paybill/PaybillFragment.kt
> +        setWatchers()
Done.

2022-01-13 12:00 UTC, alexosugo commented on app/src/main/java/com/hover/stax/paybill/PaybillFragment.kt
> +            }
This is not recursive. The `with` and `apply` keywords are helping me pass the object's context to the functions.

2022-01-13 12:01 UTC, alexosugo commented on app/src/main/java/com/hover/stax/paybill/PaybillFragment.kt
> +            Timber.e("Request composition not complete; ${actions?.firstOrNull()}, $channel $account")
Yes, passing null to Timber will cause it to crash but not when it's part of a String. In this case, it'll just print out null safely.

2022-01-13 12:04 UTC, alexosugo commented on app/src/main/java/com/hover/stax/paybill/PaybillViewModel.kt
> +            }
I was trying to avoid using too many listener interfaces by doing this.

2022-01-13 12:04 UTC, alexosugo commented on app/src/main/java/com/hover/stax/paybill/PaybillViewModel.kt
> +        }
Same as above.

2022-01-13 12:05 UTC, alexosugo commented on app/src/main/java/com/hover/stax/paybill/PaybillListFragment.kt
> +        }
Renamed to be clearer.

2022-01-25 06:52 UTC, merged