Info system component
UseHover/Stax pull request #445
Opened 2022-04-10 17:01 UTC by androidmaven

2022-04-11 08:57 UTC, alexosugo requested changes

2022-04-11 08:57 UTC, alexosugo commented on app/src/main/java/com/hover/stax/utils/Utils.kt
> +    fun getActivity(context: Context): Activity? {
If you find yourself needing to do this, then you've complicated your solution. Context should be injected, inferred or passed in most cases.

2022-04-11 08:57 UTC, alexosugo commented on app/src/main/java/com/hover/stax/views/StaxInfoTextView.kt
> +class StaxInfoTextView(context: Context, attrs: AttributeSet) : FrameLayout(context, attrs) {
Use plain XML to simplify this. It's a simple component that doesn't introduce any new complex functionality. Consider XML layouts first before creating custom components.

2022-04-11 08:57 UTC, alexosugo commented on app/src/main/java/com/hover/stax/views/StaxInfoTextView.kt
> +			Utils.getActivity(context)?.let {
Activity/fragment lifecycle may impact access to context here. See comment above on context in Utils.

2022-04-14 15:54 UTC, davkutalek approved these changes

2022-04-15 00:56 UTC, merged