Bug fix for: Get paid navigation crashing from transfer fragment.
UseHover/Stax pull request #449
Opened 2022-04-14 14:28 UTC by androidmaven

- Cause was that AbstractFormFragment was trying to make use of the same observer from different lifecycles.

- Solution was to move those observers to their individual lifecycle i.e fragment.

2022-04-14 18:05 UTC, davkutalek commented
@androidmaven this explanation doesn't quite make sense: Each of those fragments is inheriting from AbstractFormFragment and their lifecycles are totally separate even tho they share the same code base.

The cause appears to be something weird in the compiler that causes it to treat the observer as static if it appears to be the same thing. See this for a sort of expanation https://stackoverflow.com/questions/47025233/android-lifecycle-library-cannot-add-the-same-observer-with-different-lifecycle maybe @alexosugo can shed more light.

I was able to fix it the way that post says by changing the logging calls:
`Timber.e("Got new actions ${this.javaClass.simpleName}: %s", it?.size)`
I think this is preferable since otherwise the abstract class is delegating required set-up to its inheritors.

2022-04-14 18:06 UTC, davkutalek requested changes
See above comment

2022-04-15 01:40 UTC, androidmaven commented on app/src/main/java/com/hover/stax/RoutingActivity.kt
> +        Hover.setBranding(getString(R.string.app_name), R.mipmap.stax,  this)
Done, thanks.

2022-04-15 01:41 UTC, androidmaven commented
> 

Thanks for the correction @davkutalek.

I did check out the StackOverflow link earlier while attempting to fix the bug, but over-looked particularly ${this.javaClass.simpleName}.

2022-04-15 17:42 UTC, davkutalek approved these changes
LGTM

2022-04-19 10:53 UTC, merged