177364340 bounty retrybutton
UseHover/Stax pull request #59
Opened 2021-03-30 14:35 UTC by androidmaven

2021-03-30 20:14 UTC, davkutalek commented
This doesn't match the designed flow properly: After the USSD session has been recorded and finished the user should automatically be directed to the transaction details page, not stay on the bounty list. Submitted should not be a variable on the transaction model, it should just be information passed in the intent to the transaction details page. The transaction details page should always show the retry button if it is in the pending state.

2021-03-30 20:15 UTC, davkutalek requested changes
This doesn't match the designed flow properly: After the USSD session has been recorded and finished the user should automatically be directed to the transaction details page, not stay on the bounty list. Submitted should not be a variable on the transaction model, it should just be information passed in the intent to the transaction details page. The transaction details page should always show the retry button if it is in the pending state.

2021-03-31 08:57 UTC, androidmaven commented
Thank you @davkutalek for the correction. The latest push commits addresses your comments.

2021-03-31 18:28 UTC, davkutalek approved these changes
LGTM, 2 minor comments.

2021-03-31 22:26 UTC, androidmaven commented on app/src/main/res/values/logging_strings.xml
> +	<string name="clicked_retry_bounty_session">Clicked retry bounty from transaction detail page: $%1$s </string>
Got it, thanks!

2021-03-31 22:26 UTC, androidmaven commented on app/src/main/java/com/hover/stax/bounties/BountyActivity.java
> +	public void retryCall(String actionId) {
The flow wasn't added in XD, but will ask Justin

2021-03-31 22:26 UTC, merged