177626303 smarter contact matching
UseHover/Stax pull request #68
Opened 2021-04-19 13:29 UTC by androidmaven

2021-04-20 16:52 UTC, davkutalek requested changes
Looks good! Just one change please

2021-04-20 16:52 UTC, davkutalek commented on app/src/main/java/com/hover/stax/transfers/TransferActivity.java
> +				transferViewModel.setRecipientSmartly(request, channelDropdownViewModel.getActiveChannel().getValue());
setRecipientSmartly should be called from the fragment. There is already an observer there for request, so this should go in the load function which is called when the request is loaded from the DB. Same to the channel observer, there is already one there, use it instead.

2021-04-22 08:09 UTC, alexosugo approved these changes

2021-04-22 08:09 UTC, alexosugo approved these changes

2021-04-22 08:10 UTC, merged