Navigation Improvements
UseHover/Stax pull request #76
Opened 2021-04-27 07:53 UTC by alexosugo

- Replaces BottomAppBar with BottomNavigationView. 
- Reworks app-wide navigation for easier usage. 
- Adds ActionBar to handle back navigation from top level menu items. 
- Minor improvements.

2021-04-28 12:15 UTC, androidmaven requested changes
This is great work done.

1. However, the back button doesn't function. Balances, settings and back button doesn't match the design. We already support a back button functionality which by default has GONE visibility instead of having to create a new support action bar.

2. Bottom navigation doesn't have correct fonts.

2021-04-28 12:39 UTC, alexosugo commented
- I am aware of the hidden back button that was previously at the bottom bar. The `BottomAppBar` has been replaced with a `BottomNavigationView` which functions differently. The navigation change requested involved removing it from the bottom and having it at the top as is. Check [here](https://www.notion.so/usehover/write-labels-for-global-nav-53dd312bc42c4c40b127081863c2ea79). 

- Which back button are you referring to? The one in the actionbar?

- As for the fonts, you can go ahead and make the update.

2021-04-28 12:50 UTC, androidmaven commented
@alexosugo 

1. Yes I understand the changes on the BottomNavigation which works really great. 

2. Yes the back button on action bar. From the notion doc "Please add the back navigation arrows back to the top left corner of the relevant cards"; Instead of creating a back navigation, it's meant to be inside the StaxNavCard, which already exists but has default of GONE visibility.

3. Sawa Sawa

2021-04-28 14:01 UTC, androidmaven reviewed
Minor reviews

2021-04-28 14:06 UTC, alexosugo commented on app/build.gradle
> +            buildConfigField "String", "SELF_DESTRUCT", "\"1620033789\"" // May 03, 2021
I wasn't sure about the correct timeframe so I put this here as a placeholder. Wanted to confirm from you what the timeline should be.

2021-04-28 14:06 UTC, alexosugo commented on app/src/main/java/com/hover/stax/balances/BalancesFragment.java
> +        ((MainActivity) getActivity()).getSupportActionBar().setTitle(null);
It didn't work when placed there. When fragments change, the control is shifted to them, this was meant to override that.

2021-04-28 14:11 UTC, alexosugo commented on app/src/main/java/com/hover/stax/home/MainActivity.java
> +		getSupportActionBar().setTitle(null);
This can be removed. It is overridden by the respective fragments.

2021-04-28 14:18 UTC, alexosugo commented on app/src/main/java/com/hover/stax/navigation/AbstractNavigationActivity.java
> +    protected void setUpNav() {
Yeah. It can.

2021-04-28 14:19 UTC, alexosugo commented on app/src/main/java/com/hover/stax/navigation/AbstractNavigationActivity.java
> +//        if(destinationId == R.id.bountyEmailFragment || destinationId == R.id.navigation_transfer || destinationId == R.id.navigation_request){
Thanks. Will clean it up.

2021-04-29 00:12 UTC, davkutalek commented
Nav isn't working for me, pressing e.g. Balances from the send money screen goes home instead of to balances. This branch also causes text input placeholders to be black. Finally, the back arrow should def go in the card, having it outside is really weird.

2021-05-05 10:08 UTC, androidmaven commented
New changes looks good codebase wise. However, there are 3 functional issues.

1. Back buttons closes the app, instead of going to the previous screen. I  guess this is caused when activity.finish was added to the nav logic.

2. Summary cards and Link account card does not show the back button

3. This bounty screen has a margin space between content and bottom nav. Also active item on nav is home instead of settings

2021-05-05 14:02 UTC, androidmaven approved these changes
LGTM, functionality also works well now

2021-05-05 14:02 UTC, merged

2021-05-05 21:07 UTC, davkutalek commented
@alexosugo Still one issue: When you go to a view that isn't in the global nav such as send money or the bounty list then it's parent shouldn't be highlighted in the nav and tapping it's parent option in the global nav should take you to that parent page. So for example if I'm on send money, the home nav should not be blue and pressing it should take me home.

2021-05-05 21:12 UTC, davkutalek commented
also missing back from new request